/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.velocity.GetVelocityReq', null, global);
goog.exportSymbol('proto.velocity.GetVelocityRes', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.velocity.GetVelocityReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.velocity.GetVelocityReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.velocity.GetVelocityReq.displayName = 'proto.velocity.GetVelocityReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.velocity.GetVelocityReq.prototype.toObject = function(opt_includeInstance) {
  return proto.velocity.GetVelocityReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.velocity.GetVelocityReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.velocity.GetVelocityReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    cookie: msg.getCookie(),
    requesterid: msg.getRequesterid(),
    projectid: msg.getProjectid(),
    teamid: msg.getTeamid(),
    springid: msg.getSpringid()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.velocity.GetVelocityReq}
 */
proto.velocity.GetVelocityReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.velocity.GetVelocityReq;
  return proto.velocity.GetVelocityReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.velocity.GetVelocityReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.velocity.GetVelocityReq}
 */
proto.velocity.GetVelocityReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setCookie(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequesterid(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProjectid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setTeamid(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setSpringid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.velocity.GetVelocityReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.velocity.GetVelocityReq.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.velocity.GetVelocityReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.velocity.GetVelocityReq.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getCookie();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getRequesterid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getProjectid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getTeamid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getSpringid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.velocity.GetVelocityReq} The clone.
 */
proto.velocity.GetVelocityReq.prototype.cloneMessage = function() {
  return /** @type {!proto.velocity.GetVelocityReq} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string cookie = 1;
 * @return {string}
 */
proto.velocity.GetVelocityReq.prototype.getCookie = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityReq.prototype.setCookie = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string requesterId = 2;
 * @return {string}
 */
proto.velocity.GetVelocityReq.prototype.getRequesterid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityReq.prototype.setRequesterid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string projectId = 3;
 * @return {string}
 */
proto.velocity.GetVelocityReq.prototype.getProjectid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityReq.prototype.setProjectid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string teamId = 4;
 * @return {string}
 */
proto.velocity.GetVelocityReq.prototype.getTeamid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityReq.prototype.setTeamid = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string springId = 5;
 * @return {string}
 */
proto.velocity.GetVelocityReq.prototype.getSpringid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityReq.prototype.setSpringid = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.velocity.GetVelocityRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.velocity.GetVelocityRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.velocity.GetVelocityRes.displayName = 'proto.velocity.GetVelocityRes';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.velocity.GetVelocityRes.prototype.toObject = function(opt_includeInstance) {
  return proto.velocity.GetVelocityRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.velocity.GetVelocityRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.velocity.GetVelocityRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    error: msg.getError(),
    status: msg.getStatus(),
    task: msg.getTask(),
    type: msg.getType(),
    note: msg.getNote()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.velocity.GetVelocityRes}
 */
proto.velocity.GetVelocityRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.velocity.GetVelocityRes;
  return proto.velocity.GetVelocityRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.velocity.GetVelocityRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.velocity.GetVelocityRes}
 */
proto.velocity.GetVelocityRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setError(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setTask(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.velocity.GetVelocityRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.velocity.GetVelocityRes.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.velocity.GetVelocityRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.velocity.GetVelocityRes.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getError();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getStatus();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getTask();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getType();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getNote();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.velocity.GetVelocityRes} The clone.
 */
proto.velocity.GetVelocityRes.prototype.cloneMessage = function() {
  return /** @type {!proto.velocity.GetVelocityRes} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string error = 1;
 * @return {string}
 */
proto.velocity.GetVelocityRes.prototype.getError = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityRes.prototype.setError = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string status = 2;
 * @return {string}
 */
proto.velocity.GetVelocityRes.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityRes.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string task = 3;
 * @return {string}
 */
proto.velocity.GetVelocityRes.prototype.getTask = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityRes.prototype.setTask = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string type = 4;
 * @return {string}
 */
proto.velocity.GetVelocityRes.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityRes.prototype.setType = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string note = 5;
 * @return {string}
 */
proto.velocity.GetVelocityRes.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.velocity.GetVelocityRes.prototype.setNote = function(value) {
  jspb.Message.setField(this, 5, value);
};


goog.object.extend(exports, proto.velocity);
