/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.chat.SendMsgReq', null, global);
goog.exportSymbol('proto.chat.SendMsgRes', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.SendMsgReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.SendMsgReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.chat.SendMsgReq.displayName = 'proto.chat.SendMsgReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.SendMsgReq.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.SendMsgReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.SendMsgReq} msg The msg instance to transform.
 * @return {!Object}
 */
proto.chat.SendMsgReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    accesstoken: msg.getAccesstoken(),
    requesterid: msg.getRequesterid(),
    name: msg.getName(),
    channelid: msg.getChannelid(),
    msg: msg.getMsg(),
    type: msg.getType()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.SendMsgReq}
 */
proto.chat.SendMsgReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.SendMsgReq;
  return proto.chat.SendMsgReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.SendMsgReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.SendMsgReq}
 */
proto.chat.SendMsgReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccesstoken(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setRequesterid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannelid(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.chat.SendMsgReq} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.chat.SendMsgReq.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.SendMsgReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.chat.SendMsgReq.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getAccesstoken();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getRequesterid();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getName();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = this.getChannelid();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getMsg();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getType();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.chat.SendMsgReq} The clone.
 */
proto.chat.SendMsgReq.prototype.cloneMessage = function() {
  return /** @type {!proto.chat.SendMsgReq} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string accessToken = 1;
 * @return {string}
 */
proto.chat.SendMsgReq.prototype.getAccesstoken = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.chat.SendMsgReq.prototype.setAccesstoken = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string requesterId = 2;
 * @return {string}
 */
proto.chat.SendMsgReq.prototype.getRequesterid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.chat.SendMsgReq.prototype.setRequesterid = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string name = 6;
 * @return {string}
 */
proto.chat.SendMsgReq.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 6, ""));
};


/** @param {string} value  */
proto.chat.SendMsgReq.prototype.setName = function(value) {
  jspb.Message.setField(this, 6, value);
};


/**
 * optional string channelId = 3;
 * @return {string}
 */
proto.chat.SendMsgReq.prototype.getChannelid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.chat.SendMsgReq.prototype.setChannelid = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string msg = 4;
 * @return {string}
 */
proto.chat.SendMsgReq.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.chat.SendMsgReq.prototype.setMsg = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string type = 5;
 * @return {string}
 */
proto.chat.SendMsgReq.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.chat.SendMsgReq.prototype.setType = function(value) {
  jspb.Message.setField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.chat.SendMsgRes = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.chat.SendMsgRes, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.chat.SendMsgRes.displayName = 'proto.chat.SendMsgRes';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.chat.SendMsgRes.prototype.toObject = function(opt_includeInstance) {
  return proto.chat.SendMsgRes.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.chat.SendMsgRes} msg The msg instance to transform.
 * @return {!Object}
 */
proto.chat.SendMsgRes.toObject = function(includeInstance, msg) {
  var f, obj = {
    channelid: msg.getChannelid(),
    msg: msg.getMsg(),
    type: msg.getType(),
    sendername: msg.getSendername(),
    time: msg.getTime(),
    status: msg.getStatus()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.chat.SendMsgRes}
 */
proto.chat.SendMsgRes.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.chat.SendMsgRes;
  return proto.chat.SendMsgRes.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.chat.SendMsgRes} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.chat.SendMsgRes}
 */
proto.chat.SendMsgRes.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setChannelid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setMsg(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setType(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setSendername(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTime(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.chat.SendMsgRes} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.chat.SendMsgRes.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.chat.SendMsgRes.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.chat.SendMsgRes.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getChannelid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getMsg();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = this.getType();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = this.getSendername();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = this.getTime();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = this.getStatus();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
};


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.chat.SendMsgRes} The clone.
 */
proto.chat.SendMsgRes.prototype.cloneMessage = function() {
  return /** @type {!proto.chat.SendMsgRes} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional string channelId = 1;
 * @return {string}
 */
proto.chat.SendMsgRes.prototype.getChannelid = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 1, ""));
};


/** @param {string} value  */
proto.chat.SendMsgRes.prototype.setChannelid = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional string msg = 2;
 * @return {string}
 */
proto.chat.SendMsgRes.prototype.getMsg = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 2, ""));
};


/** @param {string} value  */
proto.chat.SendMsgRes.prototype.setMsg = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional string type = 3;
 * @return {string}
 */
proto.chat.SendMsgRes.prototype.getType = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 3, ""));
};


/** @param {string} value  */
proto.chat.SendMsgRes.prototype.setType = function(value) {
  jspb.Message.setField(this, 3, value);
};


/**
 * optional string senderName = 4;
 * @return {string}
 */
proto.chat.SendMsgRes.prototype.getSendername = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 4, ""));
};


/** @param {string} value  */
proto.chat.SendMsgRes.prototype.setSendername = function(value) {
  jspb.Message.setField(this, 4, value);
};


/**
 * optional string time = 5;
 * @return {string}
 */
proto.chat.SendMsgRes.prototype.getTime = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 5, ""));
};


/** @param {string} value  */
proto.chat.SendMsgRes.prototype.setTime = function(value) {
  jspb.Message.setField(this, 5, value);
};


/**
 * optional string status = 6;
 * @return {string}
 */
proto.chat.SendMsgRes.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldProto3(this, 6, ""));
};


/** @param {string} value  */
proto.chat.SendMsgRes.prototype.setStatus = function(value) {
  jspb.Message.setField(this, 6, value);
};


goog.object.extend(exports, proto.chat);
